import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dentist_app/pages/patient/AppointmentPage.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:intl/intl.dart';
import '../../CurrentPatient.dart';
import 'package:dentist_app/services/LocalizationProvider.dart';
import '../../Images.dart';
import 'BookAppointmentPage.dart';
import 'ClinicDealsPage.dart';
import 'ClinicProfilePage.dart';
import 'CouponPage.dart';
import 'InstructionsPage.dart';
import 'MyDocumentsPage.dart';
import 'SettingsPage.dart';

class PatientHomePage extends StatefulWidget {
  const PatientHomePage({super.key});

  @override
  State<PatientHomePage> createState() => PatientHomePageState();
}

class PatientHomePageState extends State<PatientHomePage>{
  final CurrentPatient currentPatient = CurrentPatient();
  bool loading = true;
  bool hasClinic = false;
  String? clinicId;
  String? clinicName;

  // CHANGED: from int numberOfAppointments to checking real appointments
  DateTime? nextAppointment;
  DateTime? lastAppointment;

  bool showInstructions = false;

  @override
  void initState() {
    super.initState();
    _loadPatient();
  }

  Future<void> _loadPatient() async {
    await currentPatient.loadFromFirestore();

    // Check if patient has a clinic
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .get();

      final data = doc.data();
      clinicId = data?['clinicId'];
      hasClinic = clinicId != null && clinicId!.isNotEmpty;

      // If has clinic, fetch clinic name
      if (hasClinic && clinicId != null) {
        try {
          final clinicDoc = await FirebaseFirestore.instance
              .collection('clinics')
              .doc(clinicId)
              .get();
          clinicName = clinicDoc.data()?['clinicName'];
        } catch (e) {
          debugPrint('Error loading clinic name: $e');
        }
      }

      // NEW: Check appointments
      await _checkAppointments(user.uid);
    }

    setState(() {
      loading = false;
    });

    // Show registration dialog if no clinic
    if (!hasClinic) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        _showClinicRegistrationDialog();
      });
    }
  }

  // NEW: Check for appointments in next/last 3 days
  Future<void> _checkAppointments(String userId) async {
    try {
      final now = DateTime.now();
      final threeDaysAhead = now.add(const Duration(days: 3));
      final threeDaysAgo = now.subtract(const Duration(days: 3));

      final snapshot = await FirebaseFirestore.instance
          .collection('appointments')
          .where('patientId', isEqualTo: userId)
          .get();

      DateTime? upcoming;
      DateTime? past;

      for (final doc in snapshot.docs) {
        final data = doc.data();
        final type = data['type'] as String? ?? 'appointment';
        if (type != 'appointment') continue;

        final startTime = (data['startTime'] as Timestamp).toDate();
        final status = data['status'] as String? ?? 'confirmed';
        if (status == 'cancelled') continue;

        // Check next 3 days
        if (startTime.isAfter(now) && startTime.isBefore(threeDaysAhead)) {
          if (upcoming == null || startTime.isBefore(upcoming)) {
            upcoming = startTime;
          }
        }

        // Check last 3 days
        if (startTime.isBefore(now) && startTime.isAfter(threeDaysAgo)) {
          if (past == null || startTime.isAfter(past)) {
            past = startTime;
          }
        }
      }

      setState(() {
        nextAppointment = upcoming;
        lastAppointment = past;
      });
    } catch (e) {
      debugPrint('Error checking appointments: $e');
    }
  }

  void _showClinicRegistrationDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => _ClinicRegistrationDialog(
        onRegister: _handleClinicRegistration,
        onSkip: () {
          Navigator.pop(context);
        },
      ),
    );
  }

  Future<void> _handleClinicRegistration(String code) async {
    Navigator.pop(context); // Close dialog

    setState(() => loading = true);

    try {
      // Normalize the entered code — trim whitespace, try uppercase first then lowercase
      final normalizedCode = code.trim().toUpperCase();
      final normalizedCodeLower = code.trim().toLowerCase();

      // Try uppercase match (codes generated by app are uppercase)
      var querySnapshot = await FirebaseFirestore.instance
          .collection('clinics')
          .where('registrationCode', isEqualTo: normalizedCode)
          .limit(1)
          .get();

      // Fallback: try exact as-entered (handles manually set lowercase codes like abc123)
      if (querySnapshot.docs.isEmpty) {
        querySnapshot = await FirebaseFirestore.instance
            .collection('clinics')
            .where('registrationCode', isEqualTo: normalizedCodeLower)
            .limit(1)
            .get();
      }

      // Fallback: try exact as typed (neither upper nor lower)
      if (querySnapshot.docs.isEmpty) {
        querySnapshot = await FirebaseFirestore.instance
            .collection('clinics')
            .where('registrationCode', isEqualTo: code.trim())
            .limit(1)
            .get();
      }

      if (querySnapshot.docs.isEmpty) {
        // Code not found
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(context.tr('invalid_registration_code')),
              backgroundColor: Colors.red,
            ),
          );
          setState(() => loading = false);
        }
        return;
      }

      final clinicDoc = querySnapshot.docs.first;
      final foundClinicId = clinicDoc.id;
      final foundClinicName = clinicDoc.data()['clinicName'];

      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        // Update patient document
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .update({
          'clinicId': foundClinicId,
          'registeredAt': FieldValue.serverTimestamp(),
        });

        // Update clinic document
        await FirebaseFirestore.instance
            .collection('clinics')
            .doc(foundClinicId)
            .update({
          'patients': FieldValue.arrayUnion([user.uid]),
        });

        // Update state
        setState(() {
          clinicId = foundClinicId;
          clinicName = foundClinicName;
          hasClinic = true;
          loading = false;
        });

        // Show success message
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('${context.tr('connected_to_clinic')}: $foundClinicName'),
              backgroundColor: const Color(0xFF7DD3C0),
              duration: const Duration(seconds: 3),
            ),
          );
        }
      }
    } catch (e) {
      debugPrint('Error registering with clinic: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${context.tr('error')}: $e'),
            backgroundColor: Colors.red,
          ),
        );
        setState(() => loading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFFFF8F0),
      body: loading
          ? const Center(child: CircularProgressIndicator())
          : SafeArea(
        child: Stack(
          children: [
            // Parallax scrolling content
            NotificationListener<ScrollNotification>(
              onNotification: (scrollNotification) {
                if (scrollNotification is ScrollUpdateNotification) {
                  setState(() {});
                }
                return false;
              },
              child: CustomScrollView(
                slivers: [
                  SliverAppBar(
                    expandedHeight: 200,
                    pinned: false,
                    floating: false,
                    backgroundColor: Colors.transparent,
                    flexibleSpace: FlexibleSpaceBar(
                      background: _buildHeroSection(),
                    ),
                  ),
                  SliverToBoxAdapter(
                    child: Container(
                      color: const Color(0xFFFFF8F0),
                      child: Column(
                        children: [
                          const SizedBox(height: 20),
                          _buildAppointmentStatusCard(),
                          const SizedBox(height: 30),
                          _buildBookAppointmentButton(),
                          const SizedBox(height: 30),
                          _buildActionCards(),
                          const SizedBox(height: 100),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
            _buildEmergencyButton(),
          ],
        ),
      ),
    );
  }

  Widget _buildHeroSection() {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFFA8E6CF), Color(0xFF7DD3C0)],
        ),
      ),
      child: Column(
        children: [
          // Top bar with settings
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Icon(Icons.notifications_outlined,
                    size: 28, color: Colors.white),
                IconButton(
                  icon: const Icon(Icons.settings, size: 28, color: Colors.white),
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => const SettingsPage()),
                    );
                  },
                ),
              ],
            ),
          ),

          // Greeting and mascot
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
            child: Column(
              children: [
                Text(
                  // CHANGED: Use patient's first name
                  currentPatient.firstName != null && currentPatient.firstName!.isNotEmpty
                      ? "היי ${currentPatient.firstName}!"
                      : "היי מר. מטופל!",
                  style: const TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  context.tr('your_smile_matters'),
                  style: const TextStyle(
                    fontSize: 16,
                    color: Colors.white,
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }


  Widget _buildAppointmentStatusCard() {
    Color borderColor;
    Color backgroundColor;
    String icon;
    String title;
    String subtitle;
    String instructionsTitle;
    List<String> instructions;

    // CHANGED: Use nextAppointment/lastAppointment instead of numberOfAppointments
    if (nextAppointment != null) {
      // Upcoming appointment
      borderColor = const Color(0xFF7DD3C0);
      backgroundColor = const Color(0xFFE8F5F1);
      icon = "🎯";
      title = context.tr('upcoming_appointment');
      subtitle = '${context.tr('next_appointment_on')} ${DateFormat('EEEE, d MMMM').format(nextAppointment!)} בשעה ${DateFormat('HH:mm').format(nextAppointment!)}';
      instructionsTitle = "לפני הטיפול";
      instructions = [
        "מומלץ לא לאכול שעה לפני הפגישה",
        "לצחצח שיניים ולנקות בחוט דנטלי היטב",
        "להגיע 10 דקות מוקדם יותר",
        "להביא את כרטיס קופת החולים שלך",
      ];
    } else if (lastAppointment != null) {
      // Post-surgery care
      borderColor = const Color(0xFFFF6B6B);
      backgroundColor = const Color(0xFFFFEBEE);
      icon = "❤️";
      title = "Post-Surgery Care";
      subtitle = "Hope you're feeling well after the surgery!";
      instructionsTitle = "Important Instructions:";
      instructions = [
        "Don't eat for 1 hour after the surgery",
        "If pain occurs, take Ibuprofen 400mg",
        "Avoid hot drinks for 24 hours",
        "Rest and take it easy today",
      ];
    } else {
      // Checkup due
      borderColor = const Color(0xFFFFB74D);
      backgroundColor = const Color(0xFFFFF3E0);
      icon = "📅";
      title = context.tr('time_for_checkup');
      subtitle = context.tr('last_checkup_6_months');
      instructionsTitle = "";
      instructions = [];
    }

    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: borderColor, width: 3),
          boxShadow: [
            BoxShadow(
              color: borderColor.withOpacity(0.2),
              blurRadius: 15,
              offset: const Offset(0, 6),
            ),
          ],
        ),
        child: Column(
          children: [
            // Header with icon and color
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: backgroundColor,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(13),
                  topRight: Radius.circular(13),
                ),
              ),
              child: Row(
                children: [
                  Text(
                    icon,
                    style: const TextStyle(fontSize: 32),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          title,
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF333333),
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          subtitle,
                          style: const TextStyle(
                            fontSize: 14,
                            color: Color(0xFF666666),
                            height: 1.4,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            // Instructions section (if applicable)
            if (instructions.isNotEmpty)
              Column(
                children: [
                  InkWell(
                    onTap: () {
                      setState(() {
                        showInstructions = !showInstructions;
                      });
                    },
                    child: Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(16),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text(
                            showInstructions ? context.tr('hide_instructions') : context.tr('view_instructions'),
                            style: TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: borderColor,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Icon(
                            showInstructions ? Icons.keyboard_arrow_up : Icons.keyboard_arrow_down,
                            color: borderColor,
                            size: 20,
                          ),
                        ],
                      ),
                    ),
                  ),
                  if (showInstructions)
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Divider(),
                          const SizedBox(height: 12),
                          Text(
                            instructionsTitle,
                            style: const TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF333333),
                            ),
                          ),
                          const SizedBox(height: 12),
                          ...instructions.map((instruction) => Padding(
                            padding: const EdgeInsets.only(bottom: 8),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  margin: const EdgeInsets.only(top: 6),
                                  width: 6,
                                  height: 6,
                                  decoration: BoxDecoration(
                                    color: borderColor,
                                    shape: BoxShape.circle,
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Text(
                                    instruction,
                                    style: const TextStyle(
                                      fontSize: 14,
                                      color: Color(0xFF666666),
                                      height: 1.4,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          )),
                        ],
                      ),
                    ),
                ],
              )
          ],
        ),
      ),
    );
  }

  Widget _buildBookAppointmentButton() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 30),
      child: Container(
        width: double.infinity,
        height: 70,
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Color(0xFF618779), Color(0xFF7DD3C0)],
          ),
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: const Color(0xFF7DD3C0).withOpacity(0.4),
              blurRadius: 20,
              offset: const Offset(0, 8),
            ),
          ],
        ),
        child: ElevatedButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                  builder: (context) => const BookAppointmentPage()),
            );
          },
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.transparent,
            shadowColor: Colors.transparent,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text(
                "📅",
                style: TextStyle(fontSize: 26),
              ),
              const SizedBox(width: 12),
              Text(
                context.tr('book_appointment'),
                style: const TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: Colors.white,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildActionCards() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: GridView.count(
        shrinkWrap: true,
        physics: const NeverScrollableScrollPhysics(),
        crossAxisCount: 2,
        mainAxisSpacing: 15,
        crossAxisSpacing: 15,
        childAspectRatio: 1.1,
        children: [
          _buildActionCardWithImage(
            icon: Images.getImage("images/discount.jpg", 36.0, 36.0),
            title: context.tr('special_discounts'),
            subtitle: context.tr('clinic_deals'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const ClinicDealsPage()),
              );
            },
          ),
          _buildActionCard(
            icon: "🗓️",
            title: context.tr('my_appointments'),
            subtitle: context.tr('view_schedule'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => const AppointmentPage()),
              );
            },
          ),
          _buildActionCardWithImage(
            icon: Images.getImage("images/medical_record.png", 36.0, 36.0),
            title: context.tr('my_medical_record'),
            subtitle: context.tr('view_documents'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const MyDocumentsPage()),
              );
            },
          ),
          _buildActionCard(
            icon: "📞",
            title: context.tr('contact_clinic'),
            subtitle: context.tr('get_in_touch'),
            onTap: () {
              // Check if patient has a clinic
              if (!hasClinic) {
                // Show registration dialog if no clinic
                _showClinicRegistrationDialog();
              } else {
                // Navigate to contact clinic page if has clinic
                Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (context) => ClinicProfilePage(clinicId: clinicId ?? '')),
                );
              }
            },
          ),
          _buildActionCard(
            icon: "📋",
            title: context.tr('instructions'),
            subtitle: "לפני ואחרי הטיפול",
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const InstructionsPage()),
              );
            },
          ),
          _buildActionCardWithImage(
            icon: Images.getImage("images/coupon.png", 36.0, 36.0),
            title: context.tr('coupons'),
            subtitle: context.tr('active_deals'),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => const CouponPage()),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildActionCard({
    required String icon,
    required String title,
    required String subtitle,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.08),
              blurRadius: 10,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              icon,
              style: const TextStyle(fontSize: 36),
            ),
            const SizedBox(height: 8),
            Text(
              title,
              style: const TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.bold,
                color: Color(0xFF333333),
              ),
              textAlign: TextAlign.center,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
            const SizedBox(height: 2),
            Text(
              subtitle,
              style: const TextStyle(
                fontSize: 11,
                color: Color(0xFF999999),
              ),
              textAlign: TextAlign.center,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildActionCardWithImage({
    required Widget icon,
    required String title,
    required String subtitle,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.08),
              blurRadius: 10,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            icon,  // Now directly using the Widget
            const SizedBox(height: 8),
            Text(
              title,
              style: const TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.bold,
                color: Color(0xFF333333),
              ),
              textAlign: TextAlign.center,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
            const SizedBox(height: 2),
            Text(
              subtitle,
              style: const TextStyle(
                fontSize: 11,
                color: Color(0xFF999999),
              ),
              textAlign: TextAlign.center,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _callEmergency() async {
    final Uri phoneUri = Uri(scheme: 'tel', path: '100');
    if (await canLaunchUrl(phoneUri)) {
      await launchUrl(phoneUri);
    }
  }

  Widget _buildEmergencyButton() {
    return Positioned(
      bottom: 30,
      right: 20,
      child: GestureDetector(
        onTap: _callEmergency,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 60,
              height: 60,
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [Color(0xFFFF8B94), Color(0xFFFF6B6B)],
                ),
                shape: BoxShape.circle,
                boxShadow: [
                  BoxShadow(
                    color: const Color(0xFFFF6B6B).withOpacity(0.4),
                    blurRadius: 15,
                    offset: const Offset(0, 5),
                  ),
                ],
              ),
              child: const Center(
                child: Text(
                  "🚨",
                  style: TextStyle(fontSize: 24),
                ),
              ),
            ),
            const SizedBox(height: 4),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.1),
                    blurRadius: 8,
                    offset: const Offset(0, 2),
                  ),
                ],
              ),
              child: Text(
                context.tr('emergency'),
                style: const TextStyle(
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFFFF6B6B),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// Clinic Registration Dialog
class _ClinicRegistrationDialog extends StatefulWidget {
  final Function(String code) onRegister;
  final VoidCallback onSkip;

  const _ClinicRegistrationDialog({
    required this.onRegister,
    required this.onSkip,
  });

  @override
  State<_ClinicRegistrationDialog> createState() => _ClinicRegistrationDialogState();
}

class _ClinicRegistrationDialogState extends State<_ClinicRegistrationDialog> {
  final _codeController = TextEditingController();

  @override
  void dispose() {
    _codeController.dispose();
    super.dispose();
  }

  void _showEnterCodeDialog() {
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Text(
          context.tr('enter_registration_code'),
          style: const TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              context.tr('ask_clinic_for_code'),
              style: const TextStyle(
                fontSize: 14,
                color: Color(0xFF666666),
              ),
            ),
            const SizedBox(height: 20),
            TextField(
              controller: _codeController,
              decoration: InputDecoration(
                labelText: context.tr('registration_code'),
                hintText: 'ABC123',
                prefixIcon: const Icon(Icons.vpn_key, color: Color(0xFF7DD3C0)),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: const BorderSide(color: Color(0xFF7DD3C0), width: 2),
                ),
              ),
              textCapitalization: TextCapitalization.characters,
              maxLength: 6,
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                letterSpacing: 2,
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext),
            child: Text(
              context.tr('cancel'),
              style: const TextStyle(color: Color(0xFF999999)),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              if (_codeController.text.isNotEmpty) {
                Navigator.pop(dialogContext);
                widget.onRegister(_codeController.text.trim());
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF7DD3C0),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            ),
            child: Text(
              context.tr('connect'),
              style: const TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _showQRCodeScanner() {
    // TODO: Implement QR code scanner
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(context.tr('qr_scanner_coming_soon')),
        backgroundColor: const Color(0xFF7DD3C0),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Icon
            Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                color: const Color(0xFF7DD3C0).withOpacity(0.2),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.local_hospital,
                size: 40,
                color: Color(0xFF7DD3C0),
              ),
            ),

            const SizedBox(height: 20),

            // Title
            Text(
              context.tr('register_clinic_now'),
              style: const TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: Color(0xFF333333),
              ),
              textAlign: TextAlign.center,
            ),

            const SizedBox(height: 12),

            // Description
            Text(
              context.tr('connect_to_dental_clinic'),
              style: const TextStyle(
                fontSize: 15,
                color: Color(0xFF666666),
                height: 1.4,
              ),
              textAlign: TextAlign.center,
            ),

            const SizedBox(height: 28),

            // Register with code button
            SizedBox(
              width: double.infinity,
              height: 56,
              child: ElevatedButton.icon(
                onPressed: _showEnterCodeDialog,
                icon: const Icon(Icons.vpn_key, size: 24),
                label: Text(
                  context.tr('register_with_code'),
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF7DD3C0),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
              ),
            ),

            const SizedBox(height: 12),

            // QR code button
            SizedBox(
              width: double.infinity,
              height: 56,
              child: OutlinedButton.icon(
                onPressed: _showQRCodeScanner,
                icon: const Icon(Icons.qr_code_scanner, size: 24),
                label: Text(
                  context.tr('scan_qr_code'),
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                style: OutlinedButton.styleFrom(
                  foregroundColor: const Color(0xFF7DD3C0),
                  side: const BorderSide(color: Color(0xFF7DD3C0), width: 2),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
              ),
            ),

            const SizedBox(height: 16),

            // Skip button
            TextButton(
              onPressed: widget.onSkip,
              child: Text(
                context.tr('skip_for_now'),
                style: const TextStyle(
                  fontSize: 14,
                  color: Color(0xFF999999),
                  decoration: TextDecoration.underline,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}