// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p1ev0FQ2fX2HdeU2oJc9gJnAphG_XqM',
    appId: '1:68651118025:web:a3dd59ebb13906c97a8c18',
    messagingSenderId: '68651118025',
    projectId: 'asnani-1f051',
    authDomain: 'asnani-1f051.firebaseapp.com',
    storageBucket: 'asnani-1f051.firebasestorage.app',
    measurementId: 'G-P0YB9S8MVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHG1Ar40ehlt0Uhge8YSIKEgATahe4xEM',
    appId: '1:68651118025:android:aa1f763a3cbace4e7a8c18',
    messagingSenderId: '68651118025',
    projectId: 'asnani-1f051',
    storageBucket: 'asnani-1f051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6NpeWazuvHlEwlmr6eIDz04dWb5YxkY',
    appId: '1:68651118025:ios:b78ccfb29d95bd0f7a8c18',
    messagingSenderId: '68651118025',
    projectId: 'asnani-1f051',
    storageBucket: 'asnani-1f051.firebasestorage.app',
    iosBundleId: 'com.example.dentistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc6NpeWazuvHlEwlmr6eIDz04dWb5YxkY',
    appId: '1:68651118025:ios:b78ccfb29d95bd0f7a8c18',
    messagingSenderId: '68651118025',
    projectId: 'asnani-1f051',
    storageBucket: 'asnani-1f051.firebasestorage.app',
    iosBundleId: 'com.example.dentistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1p1ev0FQ2fX2HdeU2oJc9gJnAphG_XqM',
    appId: '1:68651118025:web:ef4d5f53f5adff2e7a8c18',
    messagingSenderId: '68651118025',
    projectId: 'asnani-1f051',
    authDomain: 'asnani-1f051.firebaseapp.com',
    storageBucket: 'asnani-1f051.firebasestorage.app',
    measurementId: 'G-PSFL5TS8KW',
  );

}